# Generated by Django 3.1.5 on 2021-01-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210108_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cetegory',
            new_name='category',
        ),
    ]
