# Generated by Django 3.1.5 on 2021-01-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wish_list',
            field=models.ManyToManyField(blank=True, null=True, to='store.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('M', 'Mobile Phone'), ('G', 'Games and Books'), ('C', 'Computer')], max_length=1),
        ),
    ]
