# Generated by Django 3.1.5 on 2021-01-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210111_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wish_list',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
    ]
