# Generated by Django 3.1.5 on 2021-01-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210111_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wish_list',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='store.Product'),
        ),
    ]
