# Generated by Django 3.1.5 on 2021-01-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210111_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
