# Generated by Django 3.1.5 on 2021-01-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210111_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
    ]
