# Generated by Django 3.1.5 on 2021-01-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210111_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Clothes and fashion'), ('M', 'Mobile Phone'), ('G', 'Games and Books'), ('C', 'Computer')], max_length=1),
        ),
    ]
