# Generated by Django 3.1.5 on 2021-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210112_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.Product'),
        ),
    ]
