# Generated by Django 3.1.5 on 2021-01-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210113_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Clothes and fashion'), ('M', 'Mobile Phone'), ('G', 'Games and Books'), ('C', 'Computer and electronics')], max_length=1),
        ),
    ]
