# Generated by Django 3.1.5 on 2021-01-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210113_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='recommended',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='store.Product'),
        ),
    ]
