# Generated by Django 3.1.5 on 2021-01-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20210113_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces',
            field=models.IntegerField(default=1),
        ),
    ]
